### ISSUE TITLE
New icon / logo

### ISSUE THREAD

**Issue by mansya** [alexnavarro/Capstone-Project#1]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by alexnavarro** [comment]
Hi mansya how are you?

Sorry for long time to response you. Its project is a little frozen. I don't know if it worth for you.

**Comment by mansya** [comment]
I have design icon for this project. do you like it ? what do you think ?
![scheduling](https://user-images.githubusercontent.com/33461607/41667160-7e6aef92-74d6-11e8-9b35-e5ed1407c502.png)
sorry for his late response as well.

**Comment by mansya** [comment]
hi sir. How ? can I continue to make pull requests about this logo?
